@exec($__ONE_COMPONENT_REGISTRY__ = []) {{-- Khai báo để sử dụng các component đã đăng ký trong $__ONE_COMPONENT_REGISTRY__ --}}

@extends($__layout__ . "public")
    @block('content')
        <section @class([$__VIEW_ID__ . '-b4052a35', 'page-hero', 'page-hero-start'])>
            <div @class([$__VIEW_ID__ . '-90a6e493'])><p @class([$__VIEW_ID__ . '-f515bf66', 'kicker'])><span @class([$__VIEW_ID__ . '-e2f86203'])>04 / GETTING STARTED</span> Từ route đầu tiên</p><h1 @class([$__VIEW_ID__ . '-9b0938cb'])>Giữ cách Laravel nghĩ.<br @class([$__VIEW_ID__ . '-f7127348'])><em @class([$__VIEW_ID__ . '-d4f4199d'])>Thêm cách SPA chạy.</em></h1></div>
            <div @class([$__VIEW_ID__ . '-5f82dcd4', 'page-hero-aside'])><p @class([$__VIEW_ID__ . '-70182674'])>Bắt đầu từ module, route và controller quen thuộc; Saola thêm view source và pipeline biên dịch phía trên chúng.</p><dl @class([$__VIEW_ID__ . '-87f0a97e'])><div @class([$__VIEW_ID__ . '-8fd0466f'])><dt @class([$__VIEW_ID__ . '-e3488b5f'])>TIME TO MODEL</dt><dd @class([$__VIEW_ID__ . '-cf7b0d19'])>4 bước</dd></div><div @class([$__VIEW_ID__ . '-a8712dd1'])><dt @class([$__VIEW_ID__ . '-fc9334e8'])>REQUIRES</dt><dd @class([$__VIEW_ID__ . '-647f0f87'])>PHP + Node.js</dd></div></dl></div>
        </section>

        <section @class([$__VIEW_ID__ . '-8aa0772c', 'start-layout'])>
            <aside @class([$__VIEW_ID__ . '-aa1e3cea'])><span @class([$__VIEW_ID__ . '-c2b3fe81'])>TRÊN TRANG NÀY</span><a @class([$__VIEW_ID__ . '-dea58466']) @attr(['href' => '#module'])>01 / Module</a><a @class([$__VIEW_ID__ . '-a3e2bfb4']) @attr(['href' => '#view'])>02 / View</a><a @class([$__VIEW_ID__ . '-d4138949']) @attr(['href' => '#compile'])>03 / Compile</a><a @class([$__VIEW_ID__ . '-535ba0c1']) @attr(['href' => '#verify'])>04 / Verify</a></aside>
            <div @class([$__VIEW_ID__ . '-7f8af112', 'start-steps'])>
                <article @class([$__VIEW_ID__ . '-1f6b5560']) @attr(['id' => 'module'])><span @class([$__VIEW_ID__ . '-47d8cb11'])>01</span><div @class([$__VIEW_ID__ . '-ba89594d'])><p @class([$__VIEW_ID__ . '-def71512', 'kicker'])><span @class([$__VIEW_ID__ . '-23f105f9'])>ROUTE</span> Module first</p><h2 @class([$__VIEW_ID__ . '-4b7a5bc6'])>Khai báo route trong context.</h2><p @class([$__VIEW_ID__ . '-ab0a3b37'])>Module giữ controller, service và route gần nhau. Context quyết định registry và asset bundle nào phục vụ request.</p><pre @class([$__VIEW_ID__ . '-94a4005c'])><code @class([$__VIEW_ID__ . '-7ec5696d'])><span @class([$__VIEW_ID__ . '-446c4d45', 'code-line'])>System::context('web')</span><span @class([$__VIEW_ID__ . '-6dc93808', 'code-line', 'code-indent-1'])>->module('home', ['prefix' => '/'])</span><span @class([$__VIEW_ID__ . '-15f30214', 'code-line', 'code-indent-1'])>->controller(HomeController::class)</span><span @class([$__VIEW_ID__ . '-64eb60a4', 'code-line', 'code-indent-1'])>->group(function ($module) {</span><span @class([$__VIEW_ID__ . '-f7bb3fed', 'code-line', 'code-indent-2'])>$module->get('/', 'index')->name('index');</span><span @class([$__VIEW_ID__ . '-e279d126', 'code-line', 'code-indent-1'])>});</span></code></pre></div></article>
                <article @class([$__VIEW_ID__ . '-e6209cd3']) @attr(['id' => 'view'])><span @class([$__VIEW_ID__ . '-ae8d7665'])>02</span><div @class([$__VIEW_ID__ . '-58758ee5'])><p @class([$__VIEW_ID__ . '-f8b9c4b1', 'kicker'])><span @class([$__VIEW_ID__ . '-d187680d'])>VIEW</span> One source</p><h2 @class([$__VIEW_ID__ . '-4d8bc4a7'])>Tạo view <code @class([$__VIEW_ID__ . '-a4e70924'])>.sao</code>.</h2><p @class([$__VIEW_ID__ . '-122ad73f'])>Template có thể extends layout, điền block, khai báo state và gắn event. Compiler dùng cùng nguồn để tạo Blade và JavaScript.</p><pre @class([$__VIEW_ID__ . '-9a1ef381'])><code @class([$__VIEW_ID__ . '-2f148195'])><span @class([$__VIEW_ID__ . '-f8da83dd', 'code-line'])><span @class([$__VIEW_ID__ . '-44a472ba', 'directive-token'])>states({ count: 0 })</span></span><span @class([$__VIEW_ID__ . '-3f514910', 'code-line', 'code-line-gap']) @attr(['aria-hidden' => 'true'])></span><span @class([$__VIEW_ID__ . '-a266d24c', 'code-line'])><span @class([$__VIEW_ID__ . '-50915aae', 'html-token'])>template</span></span><span @class([$__VIEW_ID__ . '-9dd26e3f', 'code-line', 'code-indent-1'])><span @class([$__VIEW_ID__ . '-3cf24bec', 'directive-token'])>extends(__layout__ + "public")</span></span><span @class([$__VIEW_ID__ . '-46f645ff', 'code-line', 'code-indent-1'])><span @class([$__VIEW_ID__ . '-b842ad0d', 'directive-token'])>block('content')</span></span><span @class([$__VIEW_ID__ . '-5d31326d', 'code-line', 'code-indent-2'])><span @class([$__VIEW_ID__ . '-0935a85d', 'html-token'])>button <span @class([$__VIEW_ID__ . '-3539f645', 'directive-token'])>click(setCount(count + 1))</span></span></span><span @class([$__VIEW_ID__ . '-fb835cec', 'code-line', 'code-indent-3'])>Count: <span @class([$__VIEW_ID__ . '-3a278e82', 'mustache-token'])>count</span></span><span @class([$__VIEW_ID__ . '-07c89880', 'code-line', 'code-indent-2'])><span @class([$__VIEW_ID__ . '-2b43d542', 'html-token', 'html-token-close'])>button</span></span><span @class([$__VIEW_ID__ . '-acbcb9ed', 'code-line', 'code-indent-1'])><span @class([$__VIEW_ID__ . '-d51c4d8b', 'directive-token'])>endblock</span></span><span @class([$__VIEW_ID__ . '-879f92ac', 'code-line'])><span @class([$__VIEW_ID__ . '-c0050a20', 'html-token', 'html-token-close'])>template</span></span></code></pre></div></article>
                <article @class([$__VIEW_ID__ . '-d548dd48']) @attr(['id' => 'compile'])><span @class([$__VIEW_ID__ . '-89739934'])>03</span><div @class([$__VIEW_ID__ . '-784c7189'])><p @class([$__VIEW_ID__ . '-af5a4a4d', 'kicker'])><span @class([$__VIEW_ID__ . '-b64ca86e'])>BUILD</span> Dual output</p><h2 @class([$__VIEW_ID__ . '-21b0dbb1'])>Compile đúng context.</h2><p @class([$__VIEW_ID__ . '-cb08af7f'])>Build tạo Blade view, JavaScript view registry và bundle client tương ứng. Watch mode giữ hai output đồng bộ trong lúc phát triển.</p><pre @class([$__VIEW_ID__ . '-57bd1b01'])><code @class([$__VIEW_ID__ . '-7227e988'])><span @class([$__VIEW_ID__ . '-907e23d5', 'code-line'])>npm run build:views:web</span><span @class([$__VIEW_ID__ . '-5fdfd348', 'code-line'])>npm run build:web</span><span @class([$__VIEW_ID__ . '-e2320fc9', 'code-line', 'code-line-gap']) @attr(['aria-hidden' => 'true'])></span><span @class([$__VIEW_ID__ . '-cffa3169', 'code-line', 'code-comment'])># development</span><span @class([$__VIEW_ID__ . '-2c49ca03', 'code-line'])>npm run dev:web</span></code></pre></div></article>
                <article @class([$__VIEW_ID__ . '-641beadb']) @attr(['id' => 'verify'])><span @class([$__VIEW_ID__ . '-cfb82249'])>04</span><div @class([$__VIEW_ID__ . '-b49c74a5'])><p @class([$__VIEW_ID__ . '-24980353', 'kicker'])><span @class([$__VIEW_ID__ . '-b9eb5b9d'])>VERIFY</span> Both paths</p><h2 @class([$__VIEW_ID__ . '-c99867f7'])>Kiểm tra SSR lẫn SPA.</h2><p @class([$__VIEW_ID__ . '-d15a019c'])>Tải trực tiếp URL để xác nhận HTML đầu tiên, sau đó điều hướng nội bộ, tương tác state, back/forward và kiểm tra không có listener trùng.</p><ul @class([$__VIEW_ID__ . '-12c31522', 'check-list'])><li @class([$__VIEW_ID__ . '-ef3dd2af'])>View có nội dung khi JavaScript chưa chạy</li><li @class([$__VIEW_ID__ . '-d6abe084'])>Hydration không tạo DOM hoặc event lần hai</li><li @class([$__VIEW_ID__ . '-596911b8'])>Route context đúng với web/admin/mobile</li><li @class([$__VIEW_ID__ . '-e376ef6a'])>Rerender chỉ thay vùng reactive liên quan</li></ul></div></article>
            </div>
        </section>

        <section @class([$__VIEW_ID__ . '-6c26f9b7', 'start-cta'])><div @class([$__VIEW_ID__ . '-ce6a96bf'])><p @class([$__VIEW_ID__ . '-5a71cd5f', 'kicker'])><span @class([$__VIEW_ID__ . '-f1acc65a'])>WORKING FIXTURE</span> Đừng chỉ đọc sơ đồ</p><h2 @class([$__VIEW_ID__ . '-98293aba'])>Xem state và navigation<br @class([$__VIEW_ID__ . '-c006637c'])>trên một view đang chạy.</h2></div><a @class([$__VIEW_ID__ . '-c6b09e65', 'button', 'button-light']) @attr(['href' => '/todo-list'])>Mở Todo demo <span @class([$__VIEW_ID__ . '-3d37044f'])>↗</span></a></section>
    @endblock
