@exec($__ONE_COMPONENT_REGISTRY__ = []) {{-- Khai báo để sử dụng các component đã đăng ký trong $__ONE_COMPONENT_REGISTRY__ --}}

@extends($__layout__ . "public")
    @block('content')
        @startMarker('component', '501029e0')
        @include('web.modules.home.parts.hero')
        @endMarker('component', '501029e0')
        @startMarker('component', '142a7e71')
        @include('web.modules.home.parts.how')
        @endMarker('component', '142a7e71')
        @startMarker('component', 'cf91f6e1')
        @include('web.modules.home.parts.features')
        @endMarker('component', 'cf91f6e1')
        @startMarker('component', 'c8dd8447')
        @include('web.modules.home.parts.compare')
        @endMarker('component', 'c8dd8447')
        @startMarker('component', 'cdcde7d5')
        @include('web.modules.home.parts.usecase')
        @endMarker('component', 'cdcde7d5')
        @startMarker('component', 'eeda9939')
        @include('web.modules.home.parts.faq')
        @endMarker('component', 'eeda9939')
        @startMarker('component', 'e4c6fe66')
        @include('web.modules.home.parts.principle')
        @endMarker('component', 'e4c6fe66')
        @startMarker('component', 'ce0a61c6')
        @include('web.modules.home.parts.cta')
        @endMarker('component', 'ce0a61c6')
    @endblock
