@exec($__ONE_COMPONENT_REGISTRY__ = []) {{-- Khai báo để sử dụng các component đã đăng ký trong $__ONE_COMPONENT_REGISTRY__ --}}

@extends($__layout__ . "public")
    @block('content')
        @startMarker('component', 'Bcontentc1')
        @include('web.modules.home.parts.hero')
        @endMarker('component', 'Bcontentc1')
        @startMarker('component', 'Bcontentc2')
        @include('web.modules.home.parts.features')
        @endMarker('component', 'Bcontentc2')
        @startMarker('component', 'Bcontentc3')
        @include('web.modules.home.parts.architecture')
        @endMarker('component', 'Bcontentc3')
        @startMarker('component', 'Bcontentc4')
        @include('web.modules.home.parts.how')
        @endMarker('component', 'Bcontentc4')
        @startMarker('component', 'Bcontentc5')
        @include('web.modules.home.parts.usecase')
        @endMarker('component', 'Bcontentc5')
        @startMarker('component', 'Bcontentc6')
        @include('web.modules.home.parts.compare')
        @endMarker('component', 'Bcontentc6')
        @startMarker('component', 'Bcontentc7')
        @include('web.modules.home.parts.principle')
        @endMarker('component', 'Bcontentc7')
        @startMarker('component', 'Bcontentc8')
        @include('web.modules.home.parts.cta')
        @endMarker('component', 'Bcontentc8')
        @startMarker('component', 'Bcontentc9')
        @include('web.modules.home.parts.faq')
        @endMarker('component', 'Bcontentc9')
    @endblock
