@exec($__ONE_COMPONENT_REGISTRY__ = ['code-window' => 'web.components.code-window']) {{-- Khai báo để sử dụng các component đã đăng ký trong $__ONE_COMPONENT_REGISTRY__ --}}

@extends($__layout__ . "docs")
    @block('doc')
        <header @class([$__VIEW_ID__ . '-Bdoc1', 'page-hero'])>
            <div @class([$__VIEW_ID__ . '-Bdoc11'])>
                <p @class([$__VIEW_ID__ . '-Bdoc111', 'kicker'])><span @class([$__VIEW_ID__ . '-Bdoc1111'])>14</span> VIẾT VIEW</p>
                <h1 @class([$__VIEW_ID__ . '-Bdoc112'])>Hàm dùng được trong <code @class([$__VIEW_ID__ . '-Bdoc1121'])>&#123;&#123; &#125;&#125;</code>.</h1>
            </div>
            <div @class([$__VIEW_ID__ . '-Bdoc12', 'page-hero-aside'])>
                <p @class([$__VIEW_ID__ . '-Bdoc121'])>Một biểu thức trong template chạy hai lần bằng hai bản cài đặt khác nhau: PHP lúc SSR, JavaScript lúc CSR. Trang này là bảng tra xem tên hàm nào thật sự có ở cả hai bên.</p>
                <dl @class([$__VIEW_ID__ . '-Bdoc122'])><div @class([$__VIEW_ID__ . '-Bdoc1221'])><dt @class([$__VIEW_ID__ . '-Bdoc12211'])>CHẠY CẢ HAI</dt><dd @class([$__VIEW_ID__ . '-Bdoc12212'])>51</dd></div><div @class([$__VIEW_ID__ . '-Bdoc1222'])><dt @class([$__VIEW_ID__ . '-Bdoc12221'])>LỆCH</dt><dd @class([$__VIEW_ID__ . '-Bdoc12222'])>41</dd></div></dl>
            </div>
        </header>

        <div @class([$__VIEW_ID__ . '-Bdoc2', 'doc-body'])>
            <p @class([$__VIEW_ID__ . '-Bdoc21', 'kicker'])><span @class([$__VIEW_ID__ . '-Bdoc211'])>CƠ CHẾ</span> Vì sao lại lệch được</p>
            <h2 @class([$__VIEW_ID__ . '-Bdoc22'])>Hai bản cài đặt, một cái tên.</h2>
            <p @class([$__VIEW_ID__ . '-Bdoc23'])>Compiler không kiểm tra hàm có tồn tại hay không. Gặp một lời gọi trong biểu thức, nó chỉ quyết định gắn tiền tố nào: tên nằm trong danh sách view thì thành <code @class([$__VIEW_ID__ . '-Bdoc231'])>App.View.x()</code>, còn lại thành <code @class([$__VIEW_ID__ . '-Bdoc232'])>App.Helper.x()</code>. Nhánh Blade thì để nguyên — PHP tự phân giải lúc render.</p>
            <div @class([$__VIEW_ID__ . '-Bdoc24', 'code-window', 'code-window-dark'])>
                <div @class([$__VIEW_ID__ . '-Bdoc241', 'window-bar'])><span @class([$__VIEW_ID__ . '-Bdoc2411'])>MỘT BIỂU THỨC</span><b @class([$__VIEW_ID__ . '-Bdoc2412'])>hai đầu ra</b></div>
                <pre @class([$__VIEW_ID__ . '-Bdoc242'])><code @class([$__VIEW_ID__ . '-Bdoc2421'])><span @class([$__VIEW_ID__ . '-Bdoc24211', 'code-line'])>&lt;p&gt;&#123;&#123; number_format(total) &#125;&#125;&lt;/p&gt;</span><span @class([$__VIEW_ID__ . '-Bdoc24212', 'code-line', 'code-gap'])></span><span @class([$__VIEW_ID__ . '-Bdoc24213', 'code-line', 'code-indent-1'])>├─ blade  →  &#123;&#123; number_format($total) &#125;&#125;        (hàm builtin của PHP)</span><span @class([$__VIEW_ID__ . '-Bdoc24214', 'code-line', 'code-indent-1'])>└─ js     →  App.Helper.number_format(total)   (method của HelperService)</span></code></pre>
            </div>
            <div @class([$__VIEW_ID__ . '-Bdoc25', 'ov-note', 'ov-note--warn'])>
                Hệ quả: một cái tên chỉ có ở một bên sẽ <strong @class([$__VIEW_ID__ . '-Bdoc251'])>compile sạch, SSR ra HTML đúng, rồi nổ lúc hydrate</strong> — hoặc ngược lại. Không có cảnh báo nào ở khâu build. Bảng dưới là danh sách đã đối chiếu bằng cách quét <code @class([$__VIEW_ID__ . '-Bdoc252'])>KnownFunctions::KNOWN</code> phía compiler với <code @class([$__VIEW_ID__ . '-Bdoc253'])>HelperService</code> phía client, và với hàm builtin PHP cộng helper của Laravel và của core.
            </div>

            <p @class([$__VIEW_ID__ . '-Bdoc26', 'kicker'])><span @class([$__VIEW_ID__ . '-Bdoc261'])>AN TOÀN</span> Dùng thoải mái</p>
            <h2 @class([$__VIEW_ID__ . '-Bdoc27'])>51 tên có mặt ở cả hai phía.</h2>
            <p @class([$__VIEW_ID__ . '-Bdoc28'])>Đây là vùng dùng được mà không phải nghĩ. Phần lớn là hàm builtin của PHP đã được cài lại bằng JavaScript trong <code @class([$__VIEW_ID__ . '-Bdoc281'])>HelperService</code>, giữ nguyên tên và thứ tự tham số.</p>
            <div @class([$__VIEW_ID__ . '-Bdoc29', 'ov-tags'])>
                <span @class([$__VIEW_ID__ . '-Bdoc291', 'ov-tag'])>count</span><span @class([$__VIEW_ID__ . '-Bdoc292', 'ov-tag'])>strlen</span><span @class([$__VIEW_ID__ . '-Bdoc293', 'ov-tag'])>substr</span><span @class([$__VIEW_ID__ . '-Bdoc294', 'ov-tag'])>trim</span><span @class([$__VIEW_ID__ . '-Bdoc295', 'ov-tag'])>ltrim</span><span @class([$__VIEW_ID__ . '-Bdoc296', 'ov-tag'])>rtrim</span><span @class([$__VIEW_ID__ . '-Bdoc297', 'ov-tag'])>strtolower</span><span @class([$__VIEW_ID__ . '-Bdoc298', 'ov-tag'])>strtoupper</span><span @class([$__VIEW_ID__ . '-Bdoc299', 'ov-tag'])>ucfirst</span><span @class([$__VIEW_ID__ . '-Bdoc29e10_', 'ov-tag'])>lcfirst</span><span @class([$__VIEW_ID__ . '-Bdoc29e11_', 'ov-tag'])>str_replace</span><span @class([$__VIEW_ID__ . '-Bdoc29e12_', 'ov-tag'])>explode</span><span @class([$__VIEW_ID__ . '-Bdoc29e13_', 'ov-tag'])>implode</span><span @class([$__VIEW_ID__ . '-Bdoc29e14_', 'ov-tag'])>number_format</span>
                <span @class([$__VIEW_ID__ . '-Bdoc29e15_', 'ov-tag'])>abs</span><span @class([$__VIEW_ID__ . '-Bdoc29e16_', 'ov-tag'])>min</span><span @class([$__VIEW_ID__ . '-Bdoc29e17_', 'ov-tag'])>max</span><span @class([$__VIEW_ID__ . '-Bdoc29e18_', 'ov-tag'])>ceil</span><span @class([$__VIEW_ID__ . '-Bdoc29e19_', 'ov-tag'])>floor</span><span @class([$__VIEW_ID__ . '-Bdoc29e20_', 'ov-tag'])>round</span><span @class([$__VIEW_ID__ . '-Bdoc29e21_', 'ov-tag'])>sqrt</span>
                <span @class([$__VIEW_ID__ . '-Bdoc29e22_', 'ov-tag'])>is_array</span><span @class([$__VIEW_ID__ . '-Bdoc29e23_', 'ov-tag'])>is_null</span><span @class([$__VIEW_ID__ . '-Bdoc29e24_', 'ov-tag'])>is_numeric</span><span @class([$__VIEW_ID__ . '-Bdoc29e25_', 'ov-tag'])>is_string</span><span @class([$__VIEW_ID__ . '-Bdoc29e26_', 'ov-tag'])>isset</span><span @class([$__VIEW_ID__ . '-Bdoc29e27_', 'ov-tag'])>empty</span>
                <span @class([$__VIEW_ID__ . '-Bdoc29e28_', 'ov-tag'])>in_array</span><span @class([$__VIEW_ID__ . '-Bdoc29e29_', 'ov-tag'])>array_key_exists</span><span @class([$__VIEW_ID__ . '-Bdoc29e30_', 'ov-tag'])>array_merge</span><span @class([$__VIEW_ID__ . '-Bdoc29e31_', 'ov-tag'])>array_push</span><span @class([$__VIEW_ID__ . '-Bdoc29e32_', 'ov-tag'])>array_pop</span><span @class([$__VIEW_ID__ . '-Bdoc29e33_', 'ov-tag'])>array_unique</span>
                <span @class([$__VIEW_ID__ . '-Bdoc29e34_', 'ov-tag'])>json_encode</span><span @class([$__VIEW_ID__ . '-Bdoc29e35_', 'ov-tag'])>json_decode</span><span @class([$__VIEW_ID__ . '-Bdoc29e36_', 'ov-tag'])>md5</span><span @class([$__VIEW_ID__ . '-Bdoc29e37_', 'ov-tag'])>sha1</span><span @class([$__VIEW_ID__ . '-Bdoc29e38_', 'ov-tag'])>base64_encode</span><span @class([$__VIEW_ID__ . '-Bdoc29e39_', 'ov-tag'])>base64_decode</span>
                <span @class([$__VIEW_ID__ . '-Bdoc29e40_', 'ov-tag'])>date</span><span @class([$__VIEW_ID__ . '-Bdoc29e41_', 'ov-tag'])>time</span><span @class([$__VIEW_ID__ . '-Bdoc29e42_', 'ov-tag'])>mktime</span><span @class([$__VIEW_ID__ . '-Bdoc29e43_', 'ov-tag'])>strtotime</span><span @class([$__VIEW_ID__ . '-Bdoc29e44_', 'ov-tag'])>now</span><span @class([$__VIEW_ID__ . '-Bdoc29e45_', 'ov-tag'])>today</span>
                <span @class([$__VIEW_ID__ . '-Bdoc29e46_', 'ov-tag'])>collect</span><span @class([$__VIEW_ID__ . '-Bdoc29e47_', 'ov-tag'])>asset</span><span @class([$__VIEW_ID__ . '-Bdoc29e48_', 'ov-tag'])>url</span><span @class([$__VIEW_ID__ . '-Bdoc29e49_', 'ov-tag'])>old</span><span @class([$__VIEW_ID__ . '-Bdoc29e50_', 'ov-tag'])>dd</span><span @class([$__VIEW_ID__ . '-Bdoc29e51_', 'ov-tag'])>dump</span>
            </div>

            <p @class([$__VIEW_ID__ . '-Bdoc2e10_', 'kicker'])><span @class([$__VIEW_ID__ . '-Bdoc2e10_1'])>LỆCH</span> Ba nhóm phải tránh</p>
            <h2 @class([$__VIEW_ID__ . '-Bdoc2e11_'])>Cái nào hỏng, hỏng ở đâu.</h2>

            <p @class([$__VIEW_ID__ . '-Bdoc2e12_', 'ov-sub'])>SSR chạy · CSR nổ — 11 tên</p>
            <p @class([$__VIEW_ID__ . '-Bdoc2e13_'])>Đây là hàm của Laravel, chỉ có nghĩa trên server. Compiler vẫn vui vẻ dịch thành <code @class([$__VIEW_ID__ . '-Bdoc2e13_1'])>App.Helper.config(...)</code>, và <code @class([$__VIEW_ID__ . '-Bdoc2e13_2'])>HelperService</code> không có method đó — trang render đúng từ server rồi chết ngay khi client hydrate.</p>
            <div @class([$__VIEW_ID__ . '-Bdoc2e14_', 'ov-tags', 'ov-tags--warn'])>
                <span @class([$__VIEW_ID__ . '-Bdoc2e14_1', 'ov-tag'])>config</span><span @class([$__VIEW_ID__ . '-Bdoc2e14_2', 'ov-tag'])>env</span><span @class([$__VIEW_ID__ . '-Bdoc2e14_3', 'ov-tag'])>auth</span><span @class([$__VIEW_ID__ . '-Bdoc2e14_4', 'ov-tag'])>request</span><span @class([$__VIEW_ID__ . '-Bdoc2e14_5', 'ov-tag'])>response</span><span @class([$__VIEW_ID__ . '-Bdoc2e14_6', 'ov-tag'])>session</span><span @class([$__VIEW_ID__ . '-Bdoc2e14_7', 'ov-tag'])>cache</span><span @class([$__VIEW_ID__ . '-Bdoc2e14_8', 'ov-tag'])>logger</span><span @class([$__VIEW_ID__ . '-Bdoc2e14_9', 'ov-tag'])>abort</span><span @class([$__VIEW_ID__ . '-Bdoc2e14_e10_', 'ov-tag'])>redirect</span><span @class([$__VIEW_ID__ . '-Bdoc2e14_e11_', 'ov-tag'])>mix</span>
            </div>
            <div @class([$__VIEW_ID__ . '-Bdoc2e15_', 'ov-note'])>
                Cách đi vòng: đọc chúng trong controller rồi truyền xuống view qua data. Biểu thức trong template nên chỉ đụng tới biến, không đụng tới hạ tầng server.
            </div>

            <p @class([$__VIEW_ID__ . '-Bdoc2e16_', 'ov-sub'])>CSR chạy · SSR nổ — 15 tên</p>
            <p @class([$__VIEW_ID__ . '-Bdoc2e17_'])>Nhóm này ngược lại: <code @class([$__VIEW_ID__ . '-Bdoc2e17_1'])>HelperService</code> có, PHP không. Chúng là method của Carbon (<code @class([$__VIEW_ID__ . '-Bdoc2e17_2'])>$date-&gt;addDays()</code>) hoặc bản camelCase của helper core vốn viết snake_case, nên gọi như hàm toàn cục trong Blade là fatal error.</p>
            <div @class([$__VIEW_ID__ . '-Bdoc2e18_', 'directive-table'])>
                <div @class([$__VIEW_ID__ . '-Bdoc2e18_1'])><div @class([$__VIEW_ID__ . '-Bdoc2e18_11', 'dt-key'])><code @class([$__VIEW_ID__ . '-Bdoc2e18_111'])>addDays</code> <code @class([$__VIEW_ID__ . '-Bdoc2e18_112'])>addHours</code> <code @class([$__VIEW_ID__ . '-Bdoc2e18_113'])>addMinutes</code><br @class([$__VIEW_ID__ . '-Bdoc2e18_114'])><code @class([$__VIEW_ID__ . '-Bdoc2e18_115'])>subDays</code> <code @class([$__VIEW_ID__ . '-Bdoc2e18_116'])>subHours</code> <code @class([$__VIEW_ID__ . '-Bdoc2e18_117'])>subMinutes</code></div><span @class([$__VIEW_ID__ . '-Bdoc2e18_12'])>Phía PHP là method của Carbon, không phải hàm toàn cục</span><b @class([$__VIEW_ID__ . '-Bdoc2e18_13'])>ngày giờ</b></div>
                <div @class([$__VIEW_ID__ . '-Bdoc2e18_2'])><div @class([$__VIEW_ID__ . '-Bdoc2e18_21', 'dt-key'])><code @class([$__VIEW_ID__ . '-Bdoc2e18_211'])>diffInDays</code> <code @class([$__VIEW_ID__ . '-Bdoc2e18_212'])>diffInHours</code><br @class([$__VIEW_ID__ . '-Bdoc2e18_213'])><code @class([$__VIEW_ID__ . '-Bdoc2e18_214'])>diffInMinutes</code> <code @class([$__VIEW_ID__ . '-Bdoc2e18_215'])>diffInSeconds</code></div><span @class([$__VIEW_ID__ . '-Bdoc2e18_22'])>Cũng là method của Carbon</span><b @class([$__VIEW_ID__ . '-Bdoc2e18_23'])>ngày giờ</b></div>
                <div @class([$__VIEW_ID__ . '-Bdoc2e18_3'])><div @class([$__VIEW_ID__ . '-Bdoc2e18_31', 'dt-key'])><code @class([$__VIEW_ID__ . '-Bdoc2e18_311'])>formatDate</code> <code @class([$__VIEW_ID__ . '-Bdoc2e18_312'])>formatNumber</code> <code @class([$__VIEW_ID__ . '-Bdoc2e18_313'])>formatCurrency</code></div><span @class([$__VIEW_ID__ . '-Bdoc2e18_32'])>Core có bản snake_case: <code @class([$__VIEW_ID__ . '-Bdoc2e18_321'])>format_date</code>, <code @class([$__VIEW_ID__ . '-Bdoc2e18_322'])>format_number</code>, <code @class([$__VIEW_ID__ . '-Bdoc2e18_323'])>format_currency</code></span><b @class([$__VIEW_ID__ . '-Bdoc2e18_33'])>định dạng</b></div>
                <div @class([$__VIEW_ID__ . '-Bdoc2e18_4'])><div @class([$__VIEW_ID__ . '-Bdoc2e18_41', 'dt-key'])><code @class([$__VIEW_ID__ . '-Bdoc2e18_411'])>slug</code></div><span @class([$__VIEW_ID__ . '-Bdoc2e18_42'])>Core có <code @class([$__VIEW_ID__ . '-Bdoc2e18_421'])>generate_slug</code></span><b @class([$__VIEW_ID__ . '-Bdoc2e18_43'])>chuỗi</b></div>
                <div @class([$__VIEW_ID__ . '-Bdoc2e18_5'])><div @class([$__VIEW_ID__ . '-Bdoc2e18_51', 'dt-key'])><code @class([$__VIEW_ID__ . '-Bdoc2e18_511'])>truncate</code></div><span @class([$__VIEW_ID__ . '-Bdoc2e18_52'])>Phía PHP dùng <code @class([$__VIEW_ID__ . '-Bdoc2e18_521'])>Str::limit</code></span><b @class([$__VIEW_ID__ . '-Bdoc2e18_53'])>chuỗi</b></div>
            </div>

            <p @class([$__VIEW_ID__ . '-Bdoc2e19_', 'ov-sub'])>Nổ cả hai phía — 15 tên</p>
            <p @class([$__VIEW_ID__ . '-Bdoc2e20_'])>Những tên này nằm trong danh sách <code @class([$__VIEW_ID__ . '-Bdoc2e20_1'])>KNOWN</code> của compiler nhưng chưa từng được cài ở đâu cả. Chúng compile ra lời gọi hợp lệ rồi nổ ở bất kỳ phía nào chạy trước.</p>
            <div @class([$__VIEW_ID__ . '-Bdoc2e21_', 'ov-tags', 'ov-tags--warn'])>
                <span @class([$__VIEW_ID__ . '-Bdoc2e21_1', 'ov-tag'])>isMobile</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_2', 'ov-tag'])>isTablet</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_3', 'ov-tag'])>isDesktop</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_4', 'ov-tag'])>getDeviceType</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_5', 'ov-tag'])>scrollTo</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_6', 'ov-tag'])>copyToClipboard</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_7', 'ov-tag'])>isInViewport</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_8', 'ov-tag'])>getUrlParams</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_9', 'ov-tag'])>buildUrl</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_e10_', 'ov-tag'])>updateTitle</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_e11_', 'ov-tag'])>updateDescription</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_e12_', 'ov-tag'])>updateKeywords</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_e13_', 'ov-tag'])>format</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_e14_', 'ov-tag'])>parse</span><span @class([$__VIEW_ID__ . '-Bdoc2e21_e15_', 'ov-tag'])>createFromFormat</span>
            </div>
            <div @class([$__VIEW_ID__ . '-Bdoc2e22_', 'ov-note'])>
                Thay thế: <code @class([$__VIEW_ID__ . '-Bdoc2e22_1'])>isMobile()</code> dùng <code @class([$__VIEW_ID__ . '-Bdoc2e22_2'])>is_mobile()</code> của core rồi truyền xuống qua data; nhóm <code @class([$__VIEW_ID__ . '-Bdoc2e22_3'])>updateTitle</code> / <code @class([$__VIEW_ID__ . '-Bdoc2e22_4'])>updateDescription</code> / <code @class([$__VIEW_ID__ . '-Bdoc2e22_5'])>updateKeywords</code> dùng <code @class([$__VIEW_ID__ . '-Bdoc2e22_6'])>App.Head</code>; <code @class([$__VIEW_ID__ . '-Bdoc2e22_7'])>scrollTo</code> và <code @class([$__VIEW_ID__ . '-Bdoc2e22_8'])>copyToClipboard</code> gọi thẳng API trình duyệt trong <code @class([$__VIEW_ID__ . '-Bdoc2e22_9'])>&lt;script setup&gt;</code>.
            </div>

            <p @class([$__VIEW_ID__ . '-Bdoc2e23_', 'kicker'])><span @class([$__VIEW_ID__ . '-Bdoc2e23_1'])>COLLECTION</span> Chuỗi method</p>
            <h2 @class([$__VIEW_ID__ . '-Bdoc2e24_'])><code @class([$__VIEW_ID__ . '-Bdoc2e24_1'])>collect()</code> có ở cả hai phía.</h2>
            <p @class([$__VIEW_ID__ . '-Bdoc2e25_'])>Đây là cách gọn nhất để làm việc với danh sách mà không phải lo parity: <code @class([$__VIEW_ID__ . '-Bdoc2e25_1'])>collect()</code> trả về một proxy có 45 method trùng tên với Collection của Laravel, nên cùng một chuỗi method chạy được ở cả Blade lẫn JavaScript.</p>
            @startMarker('component', 'Bdoc2c1')
            @exec($__env->startSection($__ONE_COMPONENT_REGISTRY__['code-window'].'_0'))
@verbatim
<p>{{ collect(orders).where('status', 'paid').sum('total') }}</p>
@endverbatim
@exec($__env->stopSection())
@exec($__code_window__0_content = $__env->yieldContent($__ONE_COMPONENT_REGISTRY__['code-window'].'_0'))
@include('web.components.code-window', ['label' => "SAO", 'title' => "modules/report/index.sao", 'lang' => "html", '__ONE_CHILDREN_CONTENT__' => $__code_window__0_content])
@endMarker('component', 'Bdoc2c1')
            <div @class([$__VIEW_ID__ . '-Bdoc2e26_', 'ov-tags'])>
                <span @class([$__VIEW_ID__ . '-Bdoc2e26_1', 'ov-tag'])>map</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_2', 'ov-tag'])>filter</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_3', 'ov-tag'])>reject</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_4', 'ov-tag'])>reduce</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_5', 'ov-tag'])>each</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_6', 'ov-tag'])>pluck</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_7', 'ov-tag'])>where</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_8', 'ov-tag'])>whereIn</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_9', 'ov-tag'])>whereNotIn</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e10_', 'ov-tag'])>first</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e11_', 'ov-tag'])>last</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e12_', 'ov-tag'])>sum</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e13_', 'ov-tag'])>avg</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e14_', 'ov-tag'])>min</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e15_', 'ov-tag'])>max</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e16_', 'ov-tag'])>count</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e17_', 'ov-tag'])>sortBy</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e18_', 'ov-tag'])>sortByDesc</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e19_', 'ov-tag'])>groupBy</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e20_', 'ov-tag'])>keyBy</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e21_', 'ov-tag'])>unique</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e22_', 'ov-tag'])>flatten</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e23_', 'ov-tag'])>chunk</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e24_', 'ov-tag'])>take</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e25_', 'ov-tag'])>skip</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e26_', 'ov-tag'])>merge</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e27_', 'ov-tag'])>reverse</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e28_', 'ov-tag'])>values</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e29_', 'ov-tag'])>keys</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e30_', 'ov-tag'])>contains</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e31_', 'ov-tag'])>isEmpty</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e32_', 'ov-tag'])>isNotEmpty</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e33_', 'ov-tag'])>toArray</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e34_', 'ov-tag'])>join</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e35_', 'ov-tag'])>tap</span><span @class([$__VIEW_ID__ . '-Bdoc2e26_e36_', 'ov-tag'])>pipe</span>
            </div>

            <p @class([$__VIEW_ID__ . '-Bdoc2e27_', 'kicker'])><span @class([$__VIEW_ID__ . '-Bdoc2e27_1'])>QUY TẮC</span> Giữ cho khỏi lệch</p>
            <h2 @class([$__VIEW_ID__ . '-Bdoc2e28_'])>Ba câu để không phải tra lại.</h2>
            <ul @class([$__VIEW_ID__ . '-Bdoc2e29_', 'check-list'])>
                <li @class([$__VIEW_ID__ . '-Bdoc2e29_1'])>Biểu thức trong template chỉ đụng <em @class([$__VIEW_ID__ . '-Bdoc2e29_11'])>biến</em> và danh sách 51 tên ở trên. Mọi thứ khác tính sẵn trong controller hoặc trong <code @class([$__VIEW_ID__ . '-Bdoc2e29_12'])>&lt;script setup&gt;</code>.</li>
                <li @class([$__VIEW_ID__ . '-Bdoc2e29_2'])>Cần một hàm mới dùng được cả hai phía thì phải thêm ở <strong @class([$__VIEW_ID__ . '-Bdoc2e29_21'])>hai</strong> chỗ: helper PHP trong core và method cùng tên trong <code @class([$__VIEW_ID__ . '-Bdoc2e29_22'])>HelperService</code>. Thêm một bên là tạo ra một mục mới cho bảng lệch.</li>
                <li @class([$__VIEW_ID__ . '-Bdoc2e29_3'])>Nghi ngờ một tên thì thử tải thẳng URL (đường SSR) rồi điều hướng nội bộ tới đúng trang đó (đường CSR). Lệch chỉ lộ ra khi chạy đủ hai đường.</li>
            </ul>
        </div>

        <a @class([$__VIEW_ID__ . '-Bdoc3', 'doc-next']) @attr(['href' => '/docs/runtime'])>
            <div @class([$__VIEW_ID__ . '-Bdoc31'])><span @class([$__VIEW_ID__ . '-Bdoc311'])>Tiếp theo</span><strong @class([$__VIEW_ID__ . '-Bdoc312'])>Runtime & hydration</strong></div>
            <span @class([$__VIEW_ID__ . '-Bdoc32', 'button', 'button-primary'])>Đọc tiếp →</span>
        </a>
    @endblock
