@exec($__ONE_COMPONENT_REGISTRY__ = []) {{-- Khai báo để sử dụng các component đã đăng ký trong $__ONE_COMPONENT_REGISTRY__ --}}

@wrapper
<section @class([$__VIEW_ID__ . '-bbcd3398', 'home-hero']) @attr(['style' => 'position: relative; overflow: visible;'])>
        <div @class([$__VIEW_ID__ . '-88b70a58']) @attr(['style' => 'position: absolute; top: 10%; right: 5%; width: 60vw; height: 60vw; background: radial-gradient(circle, rgba(14,165,233,0.15) 0%, rgba(99,102,241,0.1) 40%, transparent 70%); z-index: -1; border-radius: 50%; pointer-events: none; filter: blur(40px);'])></div>
        <div @class([$__VIEW_ID__ . '-b545b1d4', 'home-hero-copy'])>
            <p @class([$__VIEW_ID__ . '-fa06b967', 'kicker'])><span @class([$__VIEW_ID__ . '-74be3ba7'])>SAOLA ECOSYSTEM</span> THE MODERN MONOLITH</p>
            <h1 @class([$__VIEW_ID__ . '-b13cf56e']) @attr(['style' => 'text-wrap: balance;'])>Trải nghiệm SPA mượt mà<br @class([$__VIEW_ID__ . '-ab8ccdf7'])><em @class([$__VIEW_ID__ . '-060b5a80'])>cùng backend bạn yêu thích.</em></h1>
            <p @class([$__VIEW_ID__ . '-38f64cbf', 'hero-lead'])>Phát triển Single-Page App với sự thanh lịch của server-side routing. Tận dụng trọn vẹn controller, middleware, và auth của Laravel mà không cần phải xây dựng riêng một tầng API.</p>
            <div @class([$__VIEW_ID__ . '-e19b2390', 'hero-actions'])>
                <a @class([$__VIEW_ID__ . '-2aa4d48f', 'button', 'button-primary']) @attr(['href' => '/docs/getting-started', 'style' => 'box-shadow: 0 8px 25px rgba(14,165,233,0.3); border: 1px solid rgba(255,255,255,0.2);'])>Đọc tài liệu hướng dẫn <span @class([$__VIEW_ID__ . '-e74aa461'])>↗</span></a>
                <a @class([$__VIEW_ID__ . '-f9cc4702', 'text-link']) @attr(['href' => '#features'])>Tại sao chọn Saola? <span @class([$__VIEW_ID__ . '-c0639405'])>→</span></a>
            </div>
            <dl @class([$__VIEW_ID__ . '-e0bad0db', 'hero-facts'])>
                <div @class([$__VIEW_ID__ . '-61d58743']) @attr(['style' => 'background: rgba(255,255,255,0.7); backdrop-filter: blur(10px);'])><dt @class([$__VIEW_ID__ . '-8458f5b9'])>PHONG CÁCH</dt><dd @class([$__VIEW_ID__ . '-bde4ee65'])>Server-driven</dd></div>
                <div @class([$__VIEW_ID__ . '-f2f3d2ed']) @attr(['style' => 'background: rgba(255,255,255,0.7); backdrop-filter: blur(10px);'])><dt @class([$__VIEW_ID__ . '-52e4505f'])>TRẢI NGHIỆM</dt><dd @class([$__VIEW_ID__ . '-cacb5949'])>Client-side Routing</dd></div>
                <div @class([$__VIEW_ID__ . '-54ae8251']) @attr(['style' => 'background: rgba(255,255,255,0.7); backdrop-filter: blur(10px);'])><dt @class([$__VIEW_ID__ . '-61033fcd'])>TƯƠNG THÍCH</dt><dd @class([$__VIEW_ID__ . '-3da4cf8c'])>Laravel 12+</dd></div>
            </dl>
        </div>

        <div @class([$__VIEW_ID__ . '-c882ec26', 'target-stack']) @attr(['style' => 'display: grid; gap: 20px; padding-left: 2vw; position: relative;'])>
            <div @class([$__VIEW_ID__ . '-2055e995', 'code-window', 'hero-code-block']) @attr(['style' => 'box-shadow: 0 25px 50px rgba(0,0,0,0.12); transform: rotate(-2deg) translateY(0); transition: transform 0.3s; border: 1px solid rgba(255,255,255,0.6);'])>
                <div @class([$__VIEW_ID__ . '-80187444', 'window-bar'])><span @class([$__VIEW_ID__ . '-047f0499'])>CONTROLLER</span><b @class([$__VIEW_ID__ . '-4e06cf36'])>UserController.php</b></div>
                <pre @class([$__VIEW_ID__ . '-3a427f36'])><code @class([$__VIEW_ID__ . '-a7a7cc5a'])><span @class([$__VIEW_ID__ . '-bb462263', 'code-line'])><span @class([$__VIEW_ID__ . '-c0200cbd', 'kw'])>class</span> <span @class([$__VIEW_ID__ . '-e7ca4651', 'ty'])>UserController</span> <span @class([$__VIEW_ID__ . '-4a466dc0', 'kw'])>extends</span> <span @class([$__VIEW_ID__ . '-c638f073', 'ty'])>Controller</span></span><span @class([$__VIEW_ID__ . '-93e8e1a5', 'code-line'])><span @class([$__VIEW_ID__ . '-9b2be056', 'op'])>{</span></span><span @class([$__VIEW_ID__ . '-d2bf8abb', 'code-line', 'code-indent-1'])><span @class([$__VIEW_ID__ . '-74c71822', 'kw'])>public function</span> <span @class([$__VIEW_ID__ . '-91dc3187', 'fn'])>show</span><span @class([$__VIEW_ID__ . '-63bd0b2c', 'op'])>(</span><span @class([$__VIEW_ID__ . '-b7d8ff21', 'ty'])>User</span> <span @class([$__VIEW_ID__ . '-8bd39a56', 'vr'])>$user</span><span @class([$__VIEW_ID__ . '-118e4c80', 'op'])>)</span></span><span @class([$__VIEW_ID__ . '-0f2b4e4a', 'code-line', 'code-indent-1'])><span @class([$__VIEW_ID__ . '-793be278', 'op'])>{</span></span><span @class([$__VIEW_ID__ . '-8b352f9c', 'code-line', 'code-indent-2'])><span @class([$__VIEW_ID__ . '-b00f4db5', 'kw'])>return</span> <span @class([$__VIEW_ID__ . '-c7a18ff6', 'vr'])>$this</span><span @class([$__VIEW_ID__ . '-f716b373', 'op'])>-&gt;</span><span @class([$__VIEW_ID__ . '-8191ed39', 'fn'])>response</span><span @class([$__VIEW_ID__ . '-db06798e', 'op'])>([</span></span><span @class([$__VIEW_ID__ . '-12b34e50', 'code-line', 'code-indent-3'])><span @class([$__VIEW_ID__ . '-223690f5', 'st'])>'user'</span> <span @class([$__VIEW_ID__ . '-d88f8fc6', 'op'])>=&gt;</span> <span @class([$__VIEW_ID__ . '-e76e445e', 'vr'])>$user</span><span @class([$__VIEW_ID__ . '-b2871ad5', 'op'])>,</span></span><span @class([$__VIEW_ID__ . '-a8d59a38', 'code-line', 'code-indent-2'])><span @class([$__VIEW_ID__ . '-dddfd6ec', 'op'])>]);</span></span><span @class([$__VIEW_ID__ . '-87fae7c4', 'code-line', 'code-indent-1'])><span @class([$__VIEW_ID__ . '-8e6e070d', 'op'])>}</span></span><span @class([$__VIEW_ID__ . '-17e8ef62', 'code-line'])><span @class([$__VIEW_ID__ . '-ac69e478', 'op'])>}</span></span></code></pre>
            </div>
            <div @class([$__VIEW_ID__ . '-c9206f66', 'code-window', 'code-window-dark', 'hero-code-block']) @attr(['style' => 'box-shadow: 0 30px 60px rgba(0,0,0,0.25); transform: rotate(3deg) translateY(0); transition: transform 0.3s; border: 1px solid rgba(255,255,255,0.1);'])>
                <div @class([$__VIEW_ID__ . '-83b9f047', 'window-bar'])><span @class([$__VIEW_ID__ . '-94c6c745'])>VIEW</span><b @class([$__VIEW_ID__ . '-fb69b9d8'])>user.sao</b></div>
                <pre @class([$__VIEW_ID__ . '-9df3d6f2'])><code @class([$__VIEW_ID__ . '-db709166'])><span @class([$__VIEW_ID__ . '-8f68429d', 'code-line'])><span @class([$__VIEW_ID__ . '-a7a1f6c3', 'kw'])>&#64;vars</span><span @class([$__VIEW_ID__ . '-cfe8c0cf', 'op'])>(</span><span @class([$__VIEW_ID__ . '-3c78ff3a', 'vr'])>user</span><span @class([$__VIEW_ID__ . '-bcf9584a', 'op'])>)</span></span><span @class([$__VIEW_ID__ . '-4198e723', 'code-line'])></span><span @class([$__VIEW_ID__ . '-fe9db4b4', 'code-line'])><span @class([$__VIEW_ID__ . '-3763c5bb', 'op'])>&lt;</span><span @class([$__VIEW_ID__ . '-07997a91', 'kw'])>template</span><span @class([$__VIEW_ID__ . '-78ab257d', 'op'])>&gt;</span></span><span @class([$__VIEW_ID__ . '-b990dc44', 'code-line', 'code-indent-1'])><span @class([$__VIEW_ID__ . '-5b65b19e', 'op'])>&lt;</span><span @class([$__VIEW_ID__ . '-a97387ff', 'fn'])>h1</span><span @class([$__VIEW_ID__ . '-5248ca7f', 'op'])>&gt;</span><span @class([$__VIEW_ID__ . '-879c020f', 'mustache-token'])><span @class([$__VIEW_ID__ . '-97196704', 'vr'])>user</span><span @class([$__VIEW_ID__ . '-7f8c4e42', 'op'])>[</span><span @class([$__VIEW_ID__ . '-82695b19', 'st'])>'name'</span><span @class([$__VIEW_ID__ . '-441dc656', 'op'])>]</span></span><span @class([$__VIEW_ID__ . '-0dd0a041', 'op'])>&lt;/</span><span @class([$__VIEW_ID__ . '-33860137', 'fn'])>h1</span><span @class([$__VIEW_ID__ . '-4cc5fe85', 'op'])>&gt;</span></span><span @class([$__VIEW_ID__ . '-b32ec6c2', 'code-line', 'code-indent-1'])><span @class([$__VIEW_ID__ . '-cc2db4fa', 'op'])>&lt;</span><span @class([$__VIEW_ID__ . '-4642a6a5', 'fn'])>p</span><span @class([$__VIEW_ID__ . '-628cdca6', 'op'])>&gt;</span>Tham gia từ: <span @class([$__VIEW_ID__ . '-035ddfbe', 'mustache-token'])><span @class([$__VIEW_ID__ . '-ca43bd86', 'vr'])>user</span><span @class([$__VIEW_ID__ . '-91a455d6', 'op'])>[</span><span @class([$__VIEW_ID__ . '-5d339c5d', 'st'])>'created_at'</span><span @class([$__VIEW_ID__ . '-5a94ff70', 'op'])>]</span></span><span @class([$__VIEW_ID__ . '-49188f5b', 'op'])>&lt;/</span><span @class([$__VIEW_ID__ . '-5797ef49', 'fn'])>p</span><span @class([$__VIEW_ID__ . '-e48adb8f', 'op'])>&gt;</span></span><span @class([$__VIEW_ID__ . '-4703a6e0', 'code-line'])><span @class([$__VIEW_ID__ . '-67f2e846', 'op'])>&lt;/</span><span @class([$__VIEW_ID__ . '-25a5a846', 'kw'])>template</span><span @class([$__VIEW_ID__ . '-8383312b', 'op'])>&gt;</span></span></code></pre>
            </div>
        </div>
    </section>
@endWrapper
